### ISSUE TITLE
[Bug]:can not support animation api

### ISSUE THREAD

**Issue by handoppler37** [rrweb-io/rrweb#1264] opened 2023-07-26 05:56 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

latest

### Expected Behavior

can record page changes with animation api

### Actual Behavior

can not record page changes with animation api，always show the init state

### Steps to Reproduce

    const element = document.getElementById('test')
    const webAnimation = element.animate([
      {
        transform: 'translateX(0) rotate(0deg)'
      },
      {
          transform: 'translateX(100px) rotate(0deg)'
      },
    ], {
      duration: 4000,
    });

**Comment by Juice10** [comment] 2023-08-04 10:12
Thanks for submitting, this is a duplicate of https://github.com/rrweb-io/rrweb/issues/1143

**Closed by Juice10** 2023-08-04 10:12 UTC
Labels: enhancement

**Comment by Muhammad-Taif-Khan** [comment] 2023-12-10 06:00
Hi Did you find any solution?
