### ISSUE TITLE
Node with id 'xxx' not found in ...

### ISSUE THREAD

**Issue by ZakYahi** [rrweb-io/rrweb#493] opened 2021-02-17 14:21 UTC
Hello! Thanks for the tool and the help provided on another issue.

I have a problem when I try to replay recorded events.
![image](https://user-images.githubusercontent.com/9142557/108217192-9874e300-7133-11eb-8d04-b01068d1a1eb.png)

Only the cursor is displayed and the yellow lines in console appear more that a hundred times.
And here is an example of recording (its a json file but Github does not let me upload it as one):
[test.txt](https://github.com/rrweb-io/rrweb/files/5996220/test.txt)

I saw that there was other issues (#190, #182, #166) but it was not helpful to me.

I'm using your library in an Angular project.

Thank you for your time.

**Comment by droidy12527** [comment] 2021-05-07 08:58
[replayer] Node with id '99' not found in Object
e.warn @ index.js:30
index.js:30 [replayer] Node with id '96' not found in Object.
I am getting the same error while running it on a particular timestamp, I mean when I am trying to skip some milliseconds forward. Did you find any fix for this issue?

**Comment by Charlesyyz128** [comment] 2022-06-14 08:34
I got the same error. When I replay the record, it is blank. While my code at earlier version, it works well. I don't know where the problem is.
你好，我也遇到了同样的问题，录制的文件在回放时是空白的。但是在我另一个分支的老版本代码，录制和回放能正常工作。两个分支的rrweb版本是一样的。

**Comment by jilanlan** [comment] 2022-07-20 10:25
> 

请问找到解决办法了吗？我也遇到相同的问题了

**Comment by jilanlan** [comment] 2022-07-20 10:25
请问找到解决办法了吗？我也遇到相同的问题了   @Charlesyyz128

**Comment by Mark-Fenng** [comment] 2022-10-05 07:58
The initial events don't show warnings anymore. This problem is happening case by case. If you are still facing the problem, please open a new issue with reproducible steps or events for debugging.

**Closed by Mark-Fenng** 2022-10-05 07:58 UTC

**Comment by wbcs** [comment] 2022-12-02 17:26
inlineStylesheet:true

**Comment by zy715** [comment] 2023-02-01 08:46
> inlineStylesheet:true
默认配置不就是ture吗？未过默认配置，也遇见相同问题

**Comment by zy715** [comment] 2023-02-01 08:58
> 请问找到解决办法了吗？我也遇到相同的问题了 @Charlesyyz128

请问找到问题点和解决方案了吗？ @jilanlan

**Comment by vinodjoshi12** [comment] 2024-07-17 11:07
I got the same error. When I replay the record, it is blank. While my code at earlier version
[okyc_data.json](https://github.com/user-attachments/files/16264413/okyc_data.json)
