### ISSUE TITLE
[Proposal] Resolve node ID's on record-side

### ISSUE THREAD

**Issue by marcospassos** [rrweb-io/rrweb#83] opened 2019-06-28 13:40 UTC
I want to discuss the feasibility involves resolving all node ids at record-time instead of replay-time, as it'd make the code a lot simpler and more consumer-friendly.

I've implemented the following POC that resolves node ids regardless of the order in which the observer reports them:

```typescript
private resolveAddedNodes(mutations: addedNodeMutation[]): addedNodeMutation[] {
    const previous: { [key: number]: number } = {};
    const next: { [key: number]: number } = {};

    for (let mutation of mutations) {
        if (mutation.previousId != null && mutation.previousId >= 0) {
            previous[mutation.previousId] = mutation.node.id;
        }

        if (mutation.nextId != null && mutation.nextId >= 0) {
            next[mutation.nextId] = mutation.node.id;
        }
    }

    let additions: addedNodeMutation[] = [];

    for (let mutation of mutations) {
        let {previousId, nextId} = mutation;

        if (previousId !== null && previousId < 0) {
            previousId = next[mutation.node.id];
        }

        if (nextId !== null && nextId < 0) {
            nextId = previous[mutation.node.id];
        }

        additions.push({
            parentId: mutation.parentId,
            nextId: nextId,
            previousId: previousId,
            node: mutation.node,
        });
    }

    return additions;
}
```

Could you check the feasibility of this proposal?

**Comment by Yuyz0112** [comment] 2019-06-29 15:06
@marcospassos when would you like to execute this method, after a mutation callback?

**Comment by marcospassos** [comment] 2019-06-29 16:18
I'd suggest before emitting to listeners, in the recorder

**Comment by Yuyz0112** [comment] 2019-06-30 09:21
@marcospassos So it will execute in this order, right?
```
1. mutation observer callback
2. loop mutation records
3. resolve nodes
4. emit to listeners
```

According to this [commit](https://github.com/rrweb-io/rrweb/commit/661fa6c7eb2512fe60b592bec58925afd8a39599), sometimes the newly added nodes will not show in the same mutation observer callback loop.

**Comment by marcospassos** [comment] 2019-06-30 21:19
@Yuyz0112 can you give me a real case or test when it occurs?  When it happens, what is missing? Parents, siblings, or both? Can we use a buffer in the record side, instead of the replay side?

**Comment by Yuyz0112** [comment] 2019-07-06 07:25
@marcospassos I could not reproduce that with any test suite code. And since mutation observer callback is a microtask in the event loop, your code should work and be safe.

So how about adding this resolve logic in the record side, but also keep the replay side missing node resolver logic as a double check?

**Comment by marcospassos** [comment] 2019-07-06 15:22
Thank you for analyzing it more in-depth,  @Yuyz0112.

Although I see no problem in leaving this fallback check, my personal opinion is that we should remove that part of the code until it proves necessary. Otherwise, we will never be sure that it is necessary, and we will carry this legacy code forever. If it does, at some point we'll notice that and reverse the commit that removed it.

**Comment by Yuyz0112** [comment] 2019-07-07 05:33
@marcospassos 

Agree with that. The only problem is some users may not report the issue and jus stop using it:)
So I would like to remove the resolving node logic at replay side in a single commit then we can revert it if necessary. Also, add some warning messages when users meet node with -1 id and taught them to report that so we can figure out what's happening.

BTW, would like to make a PR for this proposal in the record side?

**Comment by marcospassos** [comment] 2019-07-10 14:32
Sure :)

**Comment by marcospassos** [comment] 2019-08-25 17:31
@Yuyz0112 I did not forget this, I just didn't have time to work on it yet :)

**Closed** 2020-05-02 06:06 UTC

**Comment by eoghanmurray** [comment] 2021-01-22 17:20
I just wanted to add my 2c here w.r.t. https://github.com/rrweb-io/rrweb/commit/661fa6c7eb2512fe60b592bec58925afd8a39599

https://github.com/rrweb-io/rrweb/pull/224 added the concept of 'freezing' mutations, i.e. not emitting them immediately (if the browser page is not currently open).

I wonder could we apply a similar idea here, i.e. if we can't resolve all nodes, just let those mutation events build up until a subsequent mutation fully resolves the tree.  (I don't have first hand experience of unresolved nodes etc.)
