### ISSUE TITLE
Issue related to "maskAllInputs" option. Field visible after form submission

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb#93] opened 2019-07-15 10:49 UTC
Hi !
I have implemented the option "maskAllInputs" [(defined here)](https://github.com/rrweb-io/rrweb/commit/189df87b9dfe53ab364e673a893424d767031139#diff-27b748f43e236d90cb3bcb87af6b911e) last week and everything appears good (cf screenshot)
<img width="353" alt="Screen Shot 2019-07-15 at 11 10 38" src="https://user-images.githubusercontent.com/7370867/61205777-46ffa900-a6f1-11e9-82bb-cec9fa46c1a0.png">
But a problem seems to happen with form submission.
When the user has clicked on "submit", the credentials were not good, then he got a classic validation error.
But the email field was then totally visible with the email address of the user.

Can you have a look to that? 

@s-jakob : you have written this feature. Maybe you have an idea too :)

**Comment by xavier-heysch** [comment] 2019-08-05 07:03
@Yuyz0112 @s-jakob Any idea on a way to fix this? I have tried to find a solution but so far I fail.

**Comment by Yuyz0112** [comment] 2019-08-07 15:29
@xavier-heysch Sorry I cannot reproduce the bug. And I also checked the code, the option will affect both user input and program set value, and I don't know whether there are some other ways to set a value on the input.

**Comment by xavier-heysch** [comment] 2019-08-09 15:41
I have reproduced it in a sample project hosted (PHP, Bootstrap).

Here a video of the problem: https://recordit.co/2bqFtJfMEm

The form is really basic: email and password.

Everything is fine during the the first part of the video, the input are correctly anonymized. But when I submit the form, the page is reloaded (like when there is a form error) with the input already **not anonymized**. (The input value are set in PHP in server side, cf screenshot below)

![Screen Shot 2019-08-09 at 17 38 26](https://user-images.githubusercontent.com/7370867/62790978-8771fd00-bacc-11e9-95ef-bfc6ca20439d.png)

You can find below the RAW events JSON recorded for this here: [events.json.txt](https://github.com/rrweb-io/rrweb/files/3487026/events.json.txt)


Keep me informed :)

**Comment by Yuyz0112** [comment] 2019-08-11 12:46
@xavier-heysch Thanks for the information! Fixed in the master branch and will release it later.

**Closed** 2019-08-11 12:45 UTC
