### ISSUE TITLE
When i use it in Angular@9.1.7, it block the page

### ISSUE THREAD

**Issue by Iknowyouwill** [rrweb-io/rrweb#432] opened 2020-12-03 08:22 UTC
When i run rrweb.record(...), the page blocked immediately, then i found it's caused by mutationObserver. Maybe Angular's render emit too much mutation event, or my usage has some problem, so is there any help to resolve it?

**Comment by Mark-Fenng** [comment] 2020-12-03 08:30
Is there any error in console?

**Comment by Iknowyouwill** [comment] 2020-12-03 08:38
Nothing, not any error, it just block the page, the console is also blocked, i can't do anything but close the page.  /cry

**Comment by Mark-Fenng** [comment] 2020-12-03 08:42
Could you show me your code of  rrweb.record part

**Comment by Iknowyouwill** [comment] 2020-12-03 09:11
```
  startPageRecord() {
    console.log('start record');
    try {
      this.recordEvents = [];
      this.pageRecord = rrweb.record({
        inlineStylesheet: false,
        checkoutEveryNms: 20 * 1000,
        blockClass: 'rr-block',
        emit: (event, isCheckout) => {
          if (this.recordEvents.length >= 100) {
            this.stopPageRecord();
          } else {
            this.recordEvents.push(event)
          }
        },
        sampling: {
          mousemove: false,
          scroll: 500,
          input: 'last',
          mouseInteraction: {
            MouseUp: false,
            MouseDown: false,
            ContextMenu: false,
            DblClick: false,
            TouchStart: false,
            TouchEnd: false,
          },
        }
      })
    } catch(e) {
      console.log(e)
    }
  }
```

**Comment by Iknowyouwill** [comment] 2020-12-03 09:16
I found it can work when i first compile and refresh the page, but when i change the route and back it blocked. :-D

**Comment by Mark-Fenng** [comment] 2020-12-03 09:22
Oh, during recording process, you can't route to other urls for now.
BTW, `this.stopPageRecord()` is undefined in your code. I think you ought to call this.pageRecord().

**Comment by Yuyz0112** [comment] 2020-12-03 09:48
@Mark-Fenng @Iknowyouwill 

I believe it's ok to record frontend routes(SPA). There are some previous reports for hanging in Angular but could not reproduce with a minimum Angular setup. So a reproducible code repo will be very helpful.

**Comment by theycallmeloki** [comment] 2020-12-12 19:25
@Yuyz0112 this is a typed out example, alternatively I can submit a stackblitz if that would make debugging this easier

`
@HostListener('window:scroll', ['$event'])
  onWindowScroll() {
    const num = window.pageYOffset;
    if (num >= 60) {
      this.sticky = true;
    } else if (this.sticky && num < 10) {
      this.sticky = false;
    }
  }
`

in ts 

and 

`
<div (scroll)="onWindowScroll()">
    <div [class.sticky]="sticky">
    </div>
</div>
`
in html

`
.sticky {
  position: fixed !important;
  top: 64px;
  padding-top: 1.5em;
  overflow: hidden;
}
`

in css

Just to confirm: I am downsampling the events that are coming out of the record to about 300ms in between subsequent scroll events, but my guess is that the `@HostListener` on `window:scroll` is generating too many events for record to keep up with, I have also tried removing the scroll event altogether by replacing the scroll hook with `() => {}` which also did not work, if you are somehow able to echo the type of the event in the emit I could probably choose to ignore it when the record is happening, or maybe I can try to ignoreClass of `sticky` 

Any help appreciated

**Comment by Yuyz0112** [comment] 2021-05-22 09:20
I think this has been fixed in https://github.com/statcounter/rrweb/commit/5eccaa6460b4f12fb7aeb70702c6c94df9a5d6e5

**Closed by Yuyz0112** 2021-05-22 09:20 UTC
